# Generated by Django 5.2.3 on 2025-07-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_homepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePost',
        ),
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='author',
            new_name='category',
        ),
    ]
